import { createElement } from 'lwc/';
import Lwc_p_event_employeedetails from 'c/lwc_p_event_employeedetails';

describe('c-lwc-p-event-employeedetails', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-p-event-employeedetails', {
            is: Lwc_p_event_employeedetails
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});