import { createElement } from 'lwc/';
import Lwc_c_event_declaratively from 'c/lwc_c_event_declaratively';

describe('c-lwc-c-event-declaratively', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-c-event-declaratively', {
            is: Lwc_c_event_declaratively
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});